image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
   stage: build
   except:
     - master
     - dev
   script:
     - npm install
   cache:
     paths:
       - node_modules/

testing_lint:
  stage: test
  except:
    - master
    - dev
  script: npm run lint
  cache:
    paths:
      - node_modules/

testing_testing:
  stage: test
  except:
    - master
    - dev
  script: npm test
  coverage: /All files\s*\|\s*([\d\.]+)/
  cache:
    paths:
      - node_modules/