image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
   stage: build
   except:
     - master
     - dev
   script:
     - npm install
   artifacts:
     paths:
       - node_modules/

testing_testing:
  stage: test
  except:
    - master
    - dev
  script: npm test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/