version: "2"

services:
  iberedb:
    container_name: "iberedb"
    image: "mysql:5.7"
    ports:
      - "4302:3306"
    volumes:
      - /vol/ibere/db:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: "senha"
      MYSQL_DATABASE: "ibere"
    networks:
      - ibere-network

  ibere_api:
    container_name: "ibere_api"
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    restart: always
    env_file: .env-docker
    depends_on:
      - iberedb
    expose:
      - "4301"
    ports:
      - "4301:3000"
    command: sh -c "npm install && npm sequelize db:migrate && npm start"
    networks:
      - ibere-network

  ibere-web:
    container_name: "ibere-web"
    image: "node:10"
    working_dir: /app
    ports:
      - "4300:3000"
    environment:
      - REACT_APP_API_ENDPOINT=http://www.hml.ages.pucrs.br:4301/
    networks:
      - ibere-network
    volumes:
      - "./ibere-web:/app"
    command: sh -c "npm install && npm start"

networks:
  ibere-network:
